stages:
  - build
  - test
  - publish
  - release

default:
  tags:
    - build-gcp

variables:
  CONTAINER_REGISTRY: ${CI_REGISTRY_IMAGE}/application

before_script:
  - echo "$TRIGGER_AWX_JOB" > "$(pwd)/trigger_awx_job_$CI_PROJECT_NAME.sh"

build-check:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cp .env.example .env
    - docker build -t $CONTAINER_REGISTRY:${CI_COMMIT_SHA} -t $CONTAINER_REGISTRY:latest -f Dockerfile .
    - docker push $CONTAINER_REGISTRY:${CI_COMMIT_SHA}
    - docker push $CONTAINER_REGISTRY:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    paths:
      - .env
    expire_in: 2 hours
    when: always

build:
  stage: build
  variables:
    TARGET_HOST: "gitlab-runner"
  script:
    - bash trigger_awx_job_$CI_PROJECT_NAME.sh "build" "env_prod"
    - rm -f trigger_awx_job_$CI_PROJECT_NAME.sh
  except:
    - branches
  artifacts:
    paths:
      - .env
    expire_in: 1 days
    when: always

sonarqube-check:
  stage: test
  tags:
    - tools-gcp
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key:
      files:
        - bun.lockb
    paths:
      - .sonar/cache
      - node_modules/
  script:
    - sonar-scanner
  allow_failure: true
  except:
    - branches
  only:
    - merge_requests
    - /^([A-Za-z0-9.-]+)$/

report-sonar-to-merge-id:
  stage: test
  dependencies:
    - sonarqube-check
  tags:
    - tools-gcp
  script:
    - PROJECT_ID=$CI_PROJECT_ID
    - MERGE_IID=$CI_MERGE_REQUEST_IID
    - KEY=$KEY SONAR_TOKEN=$sonar_access_token repopo_token=$repopo_token PROJECT_ID=$PROJECT_ID MERGE_IID=$MERGE_IID bash -c 'sed -i "1s/^/project_id=$PROJECT_ID merge_iid=$MERGE_IID key=$KEY sonar_token=$sonar_access_token repopo_token=$repopo_token /" report.sh'
    - apt-get update -qy  # Install curl
    - apt-get install -y curl
    - bash report.sh
  except:
    - branches
  only:
    - merge_requests
  needs:
    - job: sonarqube-check

publish:
  stage: publish
  variables:
    TARGET_HOST: "gitlab-runner"
  script:
    - bash trigger_awx_job_$CI_PROJECT_NAME.sh "publish"
    - rm -f trigger_awx_job_$CI_PROJECT_NAME.sh
  except:
    - branches
  artifacts:
    paths:
      - .env
    expire_in: 1 days
    when: always

# staging:
#   stage: release
#   dependencies:
#     - publish
#   variables:
#     GIT_STRATEGY: none
#     ENVI: staging
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - echo "$ENV_STAGING" > "$(pwd)/.env"
#     - echo "$NOTIFIER" > "$(pwd)/notifier.sh"
#     - echo "$DOCKER_COMPOSE_NGINX" | base64 --decode > "$(pwd)/docker-compose.yml"
#     - docker compose pull application && docker compose up -d --force-recreate
#     - docker image prune -f
#     - bash notifier.sh
#   tags:
#     - staging-gcp
#   only:
#     - /^([A-Za-z0-9.-]+)$/
#   except:
#     - branches
#   artifacts:
#     paths:
#       - .env
#       - docker-compose.yml
#     expire_in: 1 days
#     when: always

# pre-production:
#   stage: release
#   variables:
#     # GIT_STRATEGY: none
#     ENVI: pre-production
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - echo "$ENV_PREPROD" > "$(pwd)/.env"
#     - echo "$NOTIFIER" > "$(pwd)/notifier.sh"
#     - echo "$DOCKER_COMPOSE_NGINX" | base64 --decode > "$(pwd)/docker-compose.yml"
#     - docker build -t $CONTAINER_REGISTRY:${CI_COMMIT_TAG} -t $CONTAINER_REGISTRY:latest -f Dockerfile .
#     - docker compose up -d --force-recreate 
#     - docker image prune -f
#     - bash notifier.sh
#   tags:
#     - preprod-gcp
#   only:
#     - /^([A-Za-z0-9.-]+)$/
#   except:
#     - branches
#   artifacts:
#     paths:
#       - .env
#       - docker-compose.yml
#     expire_in: 1 days
#     when: always
#   when: manual

# playground:
#   stage: release
#   variables:
#     # GIT_STRATEGY: none
#     ENVI: playground
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - echo "$ENV_PLAYGROUND" > "$(pwd)/.env"
#     - echo "$NOTIFIER" > "$(pwd)/notifier.sh"
#     - echo "$DOCKER_COMPOSE_NGINX" | base64 --decode > "$(pwd)/docker-compose.yml"
#     - docker build -t $CONTAINER_REGISTRY:${CI_COMMIT_TAG} -t $CONTAINER_REGISTRY:latest -f Dockerfile .
#     - docker compose up -d --force-recreate 
#     - docker image prune -f
#     - bash notifier.sh
#   tags:
#     - playground-gcp
#   only:
#     - /^([A-Za-z0-9.]+)$/
#   except:
#     - branches
#   artifacts:
#     paths:
#       - .env
#       - docker-compose.yml
#     expire_in: 1 days
#     when: always
#   when : manual

production:
  stage: release
  dependencies:
    - publish
  variables:
    TARGET_HOST: "prod-app-cluster-2"
  script:
    - bash trigger_awx_job_$CI_PROJECT_NAME.sh "production" "env_prod"
    - rm -f trigger_awx_job_$CI_PROJECT_NAME.sh
  tags:
    - production-gcp
  only:
    - /^([A-Za-z0-9.]+)$/
  except:
    - branches
  artifacts:
    paths:
      - .env
      - docker-compose.yml
    expire_in: 1 days
    when: always
  when : always